name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint && pnpm build
